### ISSUE TITLE
Please give credits

### ISSUE THREAD

**Issue by SaturnsVoid** [alepacheco/Tiked#2]
I see you have used a few of my packages and code, I kindly ask that you give credits to me.

I see you used atleast 2 of my projects; 
https://github.com/SaturnsVoid/Chrome-Password-Recovery
https://github.com/SaturnsVoid/Windows-KeyLogger

All i ask is for you to give credits where due.

**Comment by alepacheco** [comment]
- Added credits with your username and repo link in those files. If there's some other issue let me know. 
 

> You have interesting projects, sorry for copying your code without giving credit
